name: 'AI Code Audit'
description: 'Audit AI-generated code for security vulnerabilities, license violations, PII leaks, and quality issues'
author: 'Your Name'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

  scan-security:
    description: 'Enable security vulnerability scanning'
    required: false
    default: 'true'

  scan-licenses:
    description: 'Enable license violation detection'
    required: false
    default: 'true'

  scan-pii:
    description: 'Enable PII/secrets detection'
    required: false
    default: 'true'

  scan-ai-patterns:
    description: 'Enable AI-generated code pattern detection'
    required: false
    default: 'true'

  fail-on-findings:
    description: 'Fail the check if issues are found'
    required: false
    default: 'false'

  severity-threshold:
    description: 'Minimum severity to report (low, medium, high, critical)'
    required: false
    default: 'medium'

outputs:
  findings-count:
    description: 'Total number of findings'

  security-issues:
    description: 'Number of security issues found'

  license-violations:
    description: 'Number of license violations found'

  pii-leaks:
    description: 'Number of PII/secrets leaks found'

  ai-patterns:
    description: 'Number of AI pattern issues found'

runs:
  using: 'node20'
  main: 'dist/index.js'
